import { writeFileSync } from 'fs'
import { relative } from 'path'
import type { ComponentsContext, GenerateDtsOptions } from '../types'
import { isExportComponent, slash } from './utils'

function stringifyComponent(rootPath: string, component: ComponentsContext) {
  const related = `./${relative(rootPath, component.path)}`
  return `typeof import('${slash(related).replace(/\.[tj]sx$/, '')}')['${isExportComponent(component) ? component.name : 'default'}']\n`
}

export function generateDts(options: GenerateDtsOptions) {
  const {
    components,
    rootPath = process.cwd(),
    filename = 'components',
  } = options

  let dts = '/* generated by unplugin-react-components */\nexport {}\ndeclare global{\n'
  components.forEach((component) => {
    dts += `\tconst ${component.name}: ${stringifyComponent(rootPath, component)}`
  })

  writeFileSync(`${rootPath}/${filename}.d.ts`, `${dts}}`, { encoding: 'utf-8' })
}
