/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const CompA: typeof import('./src/CompA')['CompA']
	const CompB: typeof import('./src/CompB')['CompB']
	const AAA: typeof import('./src/utils')['AAA']
	const Utils: typeof import('./src/utils')['default']
	const CompC: typeof import('./src/Components/CompC')['CompC']
}